using System.Text;
using System.Text.Json;
using QaAgent.Core;

namespace QaAgent.Generation;

/// <summary>
/// Перетворює тест-сценарії (JSON) на готовий C#-клас NUnit + Playwright.
/// Увесь синтаксис — детермінований, модель лише постачає дані.
/// </summary>
public sealed class TestRenderer
{
    public string ClassName(EndpointSpec ep) => Sanitize($"{ep.Method}_{ep.Path}") + "_Tests";

    public string Render(EndpointSpec ep, IReadOnlyList<TestScenario> scenarios)
    {
        var className = ClassName(ep);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated> Згенеровано QaAgent. Не редагувати вручну — файл перегенеровується.");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ApiTests.Infrastructure;");
        sb.AppendLine("using Microsoft.Playwright;");
        sb.AppendLine("using NUnit.Framework;");
        sb.AppendLine();
        sb.AppendLine("namespace ApiTests.Generated;");
        sb.AppendLine();
        sb.AppendLine($"[TestFixture]");
        sb.AppendLine($"public class {className} : ApiTestBase");
        sb.AppendLine("{");

        var usedNames = new HashSet<string>();
        foreach (var s in scenarios)
            RenderMethod(sb, s, usedNames);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void RenderMethod(StringBuilder sb, TestScenario s, HashSet<string> usedNames)
    {
        var methodName = UniqueName(Sanitize(string.IsNullOrWhiteSpace(s.Name) ? "Scenario" : s.Name), usedNames);
        var url = BuildUrl(s);
        var verb = Verb(s.Method);
        var hasBody = s.Body is { ValueKind: not JsonValueKind.Null and not JsonValueKind.Undefined };
        var tokenGetter = s.Auth switch
        {
            "client" => "GetClientTokenAsync",
            "admin" => "GetAdminTokenAsync",
            _ => null
        };

        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(s.Description))
            sb.AppendLine($"    // {s.Description.Replace("\n", " ")}");
        sb.AppendLine("    [Test]");
        sb.AppendLine($"    [Category(\"{s.Type}\")]");
        sb.AppendLine($"    public async Task {methodName}()");
        sb.AppendLine("    {");

        if (tokenGetter is not null)
            sb.AppendLine($"        var token = await {tokenGetter}();");

        var needsOptions = hasBody || tokenGetter is not null;
        if (needsOptions)
        {
            sb.AppendLine($"        var response = await Api.{verb}Async(\"{url}\", new APIRequestContextOptions");
            sb.AppendLine("        {");

            var headers = new List<string>();
            if (tokenGetter is not null) headers.Add("[\"Authorization\"] = $\"Bearer {token}\"");
            if (hasBody) headers.Add("[\"Content-Type\"] = \"application/json\"");
            sb.AppendLine($"            Headers = new Dictionary<string, string> {{ {string.Join(", ", headers)} }}{(hasBody ? "," : "")}");

            if (hasBody)
            {
                var bodyJson = JsonSerializer.Serialize(s.Body!.Value);
                sb.AppendLine("            DataString = \"\"\"");
                sb.AppendLine(Indent(bodyJson, "            "));
                sb.AppendLine("            \"\"\"");
            }
            sb.AppendLine("        });");
        }
        else
        {
            sb.AppendLine($"        var response = await Api.{verb}Async(\"{url}\");");
        }

        if (s.ClientErrorRange)
        {
            sb.AppendLine("        Assert.That((int)response.Status, Is.InRange(400, 499),");
            sb.AppendLine("            $\"Очікували клієнтську помилку 4xx, отримали {(int)response.Status}: {await response.TextAsync()}\");");
        }
        else
        {
            sb.AppendLine($"        Assert.That((int)response.Status, Is.EqualTo({s.ExpectedStatus}),");
            sb.AppendLine($"            $\"Очікували {s.ExpectedStatus}, отримали {{(int)response.Status}}: {{await response.TextAsync()}}\");");
        }
        sb.AppendLine("    }");
    }

    private static string BuildUrl(TestScenario s)
    {
        var url = s.Path;
        foreach (var (key, value) in s.PathParams)
            url = url.Replace("{" + key + "}", Uri.EscapeDataString(value));

        if (s.QueryParams.Count > 0)
        {
            var query = string.Join("&", s.QueryParams.Select(kv =>
                $"{Uri.EscapeDataString(kv.Key)}={Uri.EscapeDataString(kv.Value)}"));
            url += (url.Contains('?') ? "&" : "?") + query;
        }
        return url;
    }

    private static string Verb(string method) => method.ToUpperInvariant() switch
    {
        "GET" => "Get",
        "POST" => "Post",
        "PUT" => "Put",
        "DELETE" => "Delete",
        "PATCH" => "Patch",
        _ => "Fetch"
    };

    private static string UniqueName(string name, HashSet<string> used)
    {
        var candidate = name;
        var i = 2;
        while (!used.Add(candidate))
            candidate = $"{name}_{i++}";
        return candidate;
    }

    private static string Sanitize(string raw)
    {
        var sb = new StringBuilder(raw.Length);
        foreach (var ch in raw)
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        var result = sb.ToString().Trim('_');
        while (result.Contains("__")) result = result.Replace("__", "_");
        if (result.Length == 0 || char.IsDigit(result[0])) result = "T_" + result;
        return result;
    }

    private static string Indent(string text, string indent) =>
        string.Join("\n", text.Split('\n').Select(line => indent + line));
}
