using System.Text;
using System.Text.Json;
using QaAgent.Core;

namespace QaAgent.Generation;

/// <summary>
/// Перетворює тест-сценарії (JSON) на готовий C#-клас NUnit + Playwright.
/// Увесь синтаксис — детермінований, модель лише постачає дані.
/// </summary>
public sealed class TestRenderer
{
    public string ClassName(EndpointSpec ep) => Sanitize($"{ep.Method}_{ep.Path}") + "_Tests";

    public string Render(EndpointSpec ep, IReadOnlyList<TestScenario> scenarios, string ns = "ApiTests.Generated")
    {
        var className = ClassName(ep);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated> Згенеровано QaAgent. Не редагувати вручну — файл перегенеровується.");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ApiTests.Infrastructure;");
        sb.AppendLine("using Microsoft.Playwright;");
        sb.AppendLine("using NUnit.Framework;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"[TestFixture]");
        sb.AppendLine($"public class {className} : ApiTestBase");
        sb.AppendLine("{");

        var usedNames = new HashSet<string>();
        foreach (var s in scenarios)
            RenderMethod(sb, s, usedNames);

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Стейтовий CRUD round-trip: create → read-back(200) → delete(2xx) → gone(404).
    /// Ловить «POST не персистить» та неконсистентні delete-контракти.
    /// </summary>
    public string RenderRoundTrip(string ns, string resource, string createPath, string byIdPath, string bodyJson,
        bool hasDelete, string createAuth, string readAuth, string deleteAuth,
        bool hasUpdate = false, string? updateBody = null, string updateAuth = "none", string? marker = null)
    {
        var cls = Sanitize(resource) + "_RoundTrip_Tests";
        var method = Sanitize(resource) + "_Crud_RoundTrip";
        var auths = new[] { createAuth, readAuth, deleteAuth, updateAuth };
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated> Згенеровано QaAgent. Не редагувати вручну — файл перегенеровується.");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ApiTests.Infrastructure;");
        sb.AppendLine("using Microsoft.Playwright;");
        sb.AppendLine("using NUnit.Framework;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("[TestFixture]");
        sb.AppendLine($"public class {cls} : ApiTestBase");
        sb.AppendLine("{");
        sb.AppendLine("    [Test]");
        sb.AppendLine("    [Category(\"roundtrip\")]");
        sb.AppendLine($"    public async Task {method}()");
        sb.AppendLine("    {");

        if (auths.Contains("admin")) sb.AppendLine("        var adminToken = await GetAdminTokenAsync();");
        if (auths.Contains("client")) sb.AppendLine("        var clientToken = await GetClientTokenAsync();");

        RoundTripRequest(sb, "createResp", "Post", createPath, createAuth, bodyJson);
        sb.AppendLine("        Assert.That((int)createResp.Status, Is.InRange(200, 299),");
        sb.AppendLine("            $\"Створення не вдалося: {(int)createResp.Status}: {await createResp.TextAsync()}\");");
        sb.AppendLine();
        sb.AppendLine("        var created = await createResp.JsonAsync();");
        sb.AppendLine("        Assert.That(created.HasValue && created.Value.TryGetProperty(\"id\", out _), Is.True,");
        sb.AppendLine("            \"Відповідь створення не містить поля 'id'.\");");
        sb.AppendLine("        var idEl = created!.Value.GetProperty(\"id\");");
        sb.AppendLine("        var id = idEl.ValueKind == JsonValueKind.String ? idEl.GetString() : idEl.GetRawText();");
        sb.AppendLine();
        RoundTripRequest(sb, "getResp", "Get", byIdPath, readAuth, null);
        sb.AppendLine("        Assert.That((int)getResp.Status, Is.EqualTo(200),");
        sb.AppendLine("            $\"Створений ресурс недоступний за id={id} (персистентність?): {(int)getResp.Status}\");");

        if (hasUpdate && updateBody is not null)
        {
            sb.AppendLine();
            RoundTripRequest(sb, "updateResp", "Put", byIdPath, updateAuth, updateBody);
            sb.AppendLine("        Assert.That((int)updateResp.Status, Is.InRange(200, 299),");
            sb.AppendLine("            $\"Оновлення не вдалося: {(int)updateResp.Status}: {await updateResp.TextAsync()}\");");
            if (marker is not null)
            {
                sb.AppendLine();
                RoundTripRequest(sb, "afterUpdate", "Get", byIdPath, readAuth, null);
                sb.AppendLine("        Assert.That((int)afterUpdate.Status, Is.EqualTo(200),");
                sb.AppendLine("            $\"Ресурс недоступний після оновлення: {(int)afterUpdate.Status}\");");
                sb.AppendLine($"        Assert.That(await afterUpdate.TextAsync(), Does.Contain(\"{marker}\"),");
                sb.AppendLine("            \"Оновлення не збереглося: змінене значення відсутнє у відповіді.\");");
            }
        }

        if (hasDelete)
        {
            sb.AppendLine();
            RoundTripRequest(sb, "delResp", "Delete", byIdPath, deleteAuth, null);
            sb.AppendLine("        Assert.That((int)delResp.Status, Is.InRange(200, 299),");
            sb.AppendLine("            $\"Видалення не вдалося: {(int)delResp.Status}\");");
            sb.AppendLine();
            RoundTripRequest(sb, "goneResp", "Get", byIdPath, readAuth, null);
            sb.AppendLine("        Assert.That((int)goneResp.Status, Is.EqualTo(404),");
            sb.AppendLine("            $\"Після видалення ресурс усе ще доступний: {(int)goneResp.Status}\");");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void RoundTripRequest(StringBuilder sb, string varName, string verb, string path, string auth, string? bodyJson)
    {
        var headers = new List<string>();
        if (auth == "admin") headers.Add("[\"Authorization\"] = $\"Bearer {adminToken}\"");
        else if (auth == "client") headers.Add("[\"Authorization\"] = $\"Bearer {clientToken}\"");
        if (bodyJson is not null) headers.Add("[\"Content-Type\"] = \"application/json\"");

        if (headers.Count == 0 && bodyJson is null)
        {
            sb.AppendLine($"        var {varName} = await Api.{verb}Async($\"{path}\");");
            return;
        }

        sb.AppendLine($"        var {varName} = await Api.{verb}Async($\"{path}\", new APIRequestContextOptions");
        sb.AppendLine("        {");
        sb.AppendLine($"            Headers = new Dictionary<string, string> {{ {string.Join(", ", headers)} }}{(bodyJson is null ? "" : ",")}");
        if (bodyJson is not null)
        {
            sb.AppendLine("            DataString = \"\"\"");
            sb.AppendLine(Indent(bodyJson, "            "));
            sb.AppendLine("            \"\"\"");
        }
        sb.AppendLine("        });");
    }

    private static void RenderMethod(StringBuilder sb, TestScenario s, HashSet<string> usedNames)
    {
        var methodName = UniqueName(Sanitize(string.IsNullOrWhiteSpace(s.Name) ? "Scenario" : s.Name), usedNames);
        var url = BuildUrl(s);
        var verb = Verb(s.Method);
        var hasBody = s.Body is { ValueKind: not JsonValueKind.Null and not JsonValueKind.Undefined };
        var tokenGetter = s.Auth switch
        {
            "client" => "GetClientTokenAsync",
            "admin" => "GetAdminTokenAsync",
            _ => null
        };

        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(s.Description))
            sb.AppendLine($"    // {s.Description.Replace("\n", " ")}");
        sb.AppendLine("    [Test]");
        sb.AppendLine($"    [Category(\"{s.Type}\")]");
        sb.AppendLine($"    public async Task {methodName}()");
        sb.AppendLine("    {");

        if (tokenGetter is not null)
            sb.AppendLine($"        var token = await {tokenGetter}();");

        var needsOptions = hasBody || tokenGetter is not null;
        if (needsOptions)
        {
            sb.AppendLine($"        var response = await Api.{verb}Async(\"{url}\", new APIRequestContextOptions");
            sb.AppendLine("        {");

            var headers = new List<string>();
            if (tokenGetter is not null) headers.Add("[\"Authorization\"] = $\"Bearer {token}\"");
            if (hasBody) headers.Add("[\"Content-Type\"] = \"application/json\"");
            sb.AppendLine($"            Headers = new Dictionary<string, string> {{ {string.Join(", ", headers)} }}{(hasBody ? "," : "")}");

            if (hasBody)
            {
                var bodyJson = JsonSerializer.Serialize(s.Body!.Value);
                sb.AppendLine("            DataString = \"\"\"");
                sb.AppendLine(Indent(bodyJson, "            "));
                sb.AppendLine("            \"\"\"");
            }
            sb.AppendLine("        });");
        }
        else
        {
            sb.AppendLine($"        var response = await Api.{verb}Async(\"{url}\");");
        }

        if (s.ClientErrorRange)
        {
            sb.AppendLine("        Assert.That((int)response.Status, Is.InRange(400, 499),");
            sb.AppendLine("            $\"Очікували клієнтську помилку 4xx, отримали {(int)response.Status}: {await response.TextAsync()}\");");
        }
        else if (s.SuccessRange)
        {
            sb.AppendLine("        Assert.That((int)response.Status, Is.InRange(200, 299),");
            sb.AppendLine("            $\"Очікували успіх 2xx, отримали {(int)response.Status}: {await response.TextAsync()}\");");
        }
        else if (s.NoServerError)
        {
            sb.AppendLine("        Assert.That((int)response.Status, Is.LessThan(500),");
            sb.AppendLine("            $\"Очікували відповідь без 5xx, отримали {(int)response.Status}: {await response.TextAsync()}\");");
        }
        else
        {
            sb.AppendLine($"        Assert.That((int)response.Status, Is.EqualTo({s.ExpectedStatus}),");
            sb.AppendLine($"            $\"Очікували {s.ExpectedStatus}, отримали {{(int)response.Status}}: {{await response.TextAsync()}}\");");
        }
        sb.AppendLine("    }");
    }

    private static string BuildUrl(TestScenario s)
    {
        // Без провідного "/" — щоб BaseURL із базовим шляхом (напр. /api/v3) не скидався.
        var url = s.Path.TrimStart('/');
        foreach (var (key, value) in s.PathParams)
            url = url.Replace("{" + key + "}", Uri.EscapeDataString(value));

        if (s.QueryParams.Count > 0)
        {
            var query = string.Join("&", s.QueryParams.Select(kv =>
                $"{Uri.EscapeDataString(kv.Key)}={Uri.EscapeDataString(kv.Value)}"));
            url += (url.Contains('?') ? "&" : "?") + query;
        }
        return url;
    }

    private static string Verb(string method) => method.ToUpperInvariant() switch
    {
        "GET" => "Get",
        "POST" => "Post",
        "PUT" => "Put",
        "DELETE" => "Delete",
        "PATCH" => "Patch",
        _ => "Fetch"
    };

    private static string UniqueName(string name, HashSet<string> used)
    {
        var candidate = name;
        var i = 2;
        while (!used.Add(candidate))
            candidate = $"{name}_{i++}";
        return candidate;
    }

    private static string Sanitize(string raw)
    {
        var sb = new StringBuilder(raw.Length);
        foreach (var ch in raw)
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        var result = sb.ToString().Trim('_');
        while (result.Contains("__")) result = result.Replace("__", "_");
        if (result.Length == 0 || char.IsDigit(result[0])) result = "T_" + result;
        return result;
    }

    private static string Indent(string text, string indent) =>
        string.Join("\n", text.Split('\n').Select(line => indent + line));
}
